In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [5]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.get_weights()

[array([[-0.58026016,  0.95435727],
        [-0.29844964,  0.09312904]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.49506593],
        [-0.578511  ]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
               np.array([0.,0.],dtype=np.float32),
               np.array([[0.1],[0.1]],dtype=np.float32),
               np.array([0.],dtype=np.float32)]

In [9]:
model.set_weights(new_weights)

In [10]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
optimizer =  keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [12]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 [==============================] - 1s 3ms/step - loss: 27.8838
Epoch 2/75
4/4 [==============================] - 0s 517us/step - loss: 27.5814
Epoch 3/75
4/4 [==============================] - 0s 7ms/step - loss: 27.2431
Epoch 4/75
4/4 [==============================] - 0s 6ms/step - loss: 26.8885
Epoch 5/75
4/4 [==============================] - 0s 8ms/step - loss: 26.5484
Epoch 6/75
4/4 [==============================] - 0s 1ms/step - loss: 26.1994
Epoch 7/75
4/4 [==============================] - 0s 5ms/step - loss: 25.8085
Epoch 8/75
4/4 [==============================] - 0s 6ms/step - loss: 25.4401
Epoch 9/75
4/4 [==============================] - 0s 6ms/step - loss: 25.0358
Epoch 10/75
4/4 [==============================] - 0s 0s/step - loss: 24.6567
Epoch 11/75
4/4 [==============================] - 0s 5ms/step - loss: 24.2202
Epoch 12/75
4/4 [==============================] - 0s 6ms/step - loss: 23.7828
Epoch 13/75
4/4 [==============================] - 0s 7ms/st

In [18]:
model.get_weights()

[array([[0.37387073, 0.37387073],
        [0.36561698, 0.36561698]], dtype=float32),
 array([0.2724311, 0.2724311], dtype=float32),
 array([[0.37302735],
        [0.37302735]], dtype=float32),
 array([0.20472449], dtype=float32)]